### ISSUE TITLE
Typed command history navigation using keyboard(changes needed in readline.c)

### ISSUE THREAD

**Issue by oneiro-naut** [oneiro-naut/wish_beta#7]
Switching to a previously typed command using UP or DOWN keys without actually typing them again.
Will require a datatype to store all the input that user enters.(a specialized STACK or QUEUE)

**Comment by eldracode** [comment]
fixed by #[f1f55a6](https://github.com/oneiro-naut/wish/commit/f1f55a6a7af209873dc0d9fbbf2e5b2fdb2458aa) .
